name: Code Climate Check

on:
  pull_request:
    branches:
      - main

jobs:
  main:
    name: Code Climate Check
    runs-on: ubuntu-latest
    steps:
      - name: Code Coverage
        uses: paambaati/codeclimate-action@v4.0.0
        with:
          coverageCommand: npx nyc report --reporter=lcov
