name: Testing suite

on:
  pull_request:
    branches:
      main

jobs:
  main:
    name: Testing suite
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - working-directory: .
      run: |
        npm ci
        npm run test